name: 'Restart ECS service'
description: 'Action to restart ecs service'
inputs:
  ACCESS_KEY_ID:
    description: 'AWS access_key_id'
    required: true
  SECRET_ACCESS_KEY:
    required: true
    description: 'AWS secret_access_key'
  REGION_NAME:
    description: 'Name of the region to be used to connect to the AWS'
    required: false
    default: 'us-east-1'
  CLUSTER_NAME:
    description: 'Name of the cluster in ECS'
    required: false
    default: 'default'
  SERVICE_NAME:
    description: 'Name of the service in ECS cluster'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.REGION_NAME }}
    - ${{ inputs.CLUSTER_NAME }}
    - ${{ inputs.SERVICE_NAME }}
    - ${{inputs.ACCESS_KEY_ID}}
    - ${{inputs.SECRET_ACCESS_KEY}}